---
title: "Journal (reproducible report)"
author: "Nils Stamm"
date: "2020-11-05"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# My first Assignmend

Last compiled: `r Sys.Date()`


## Revenue analysis by state

```{r, fig.width=10, fig.height=7}
  sales_by_state_tbl <- readRDS("data/sales_by_state_tbl.rds")

  library(ggrepel)
  sales_by_state_tbl %>%
  ggplot(aes(x = location_state, y = sales)) +
    
  geom_col(fill = "#2DC6D6") + # Use geom_col for a bar plot
  geom_label_repel(aes(label = sales_text)) + # Adding labels to the bars
  
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                      decimal.mark = ",", 
                                                      prefix = "", 
                                                      suffix = " €")) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    
  labs(
      title    = "Revenue by state",
      subtitle = "in Germany",
      x = "State", # Override defaults for x and y
      y = "Revenue")
```  
  
  
## Revenue analysis over years per state
  
```{r, fig.width=10, fig.height=7} 
  sales_by_year_state_tbl <- readRDS("data/sales_by_year_state_tbl.rds")  

  sales_by_year_state_tbl %>%
  ggplot(aes(x = year, y = sales, fill = location_state)) +
    
  geom_col() + # Run up to here to get a stacked bar plot
  geom_smooth(method = "lm", se = FALSE) + # Adding a trendline
    
  facet_wrap(~ location_state) +
    
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                      decimal.mark = ",", 
                                                      prefix = "", 
                                                      suffix = " €")) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    
  labs(
      title = "Revenue by year and state",
      subtitle = "in Germany",
      fill = "State") # Changes the legend name
```